import parafusadeira from "@/assets/produto-parafusadeira.jpg";
import esmerilhadeira from "@/assets/produto-esmerilhadeira.jpg";
import furadeira from "@/assets/produto-furadeira.jpg";
import serra from "@/assets/produto-serra.jpg";
import kit from "@/assets/produto-kit-ferramentas.jpg";
import { products } from "@/lib/catalog";

export type StoreProduct = {
  id: string;
  name: string;
  image: string;
  price: number;
  oldPrice: number;
  discount: number;
  rating: number;
  reviews: number;
  sold: number;
  freeShipping: boolean;
  description: string;
  /** se for produto comprável, link interno; senão null (exibe "Indisponível") */
  href: string | null;
  /** slug do produto no catálogo (apenas para produtos compráveis) */
  slug?: string;
};

const lavadora = products.find((p) => p.id === "lav-1300")!;
const aspirador = products.find((p) => p.id === "asp-6000")!;
const relogio = products.find((p) => p.id === "rel-pallyjane")!;
const garrafa = products.find((p) => p.id === "garrafa-fresh-aparecida")!;
const boombox = products.find((p) => p.id === "boombox-aiwa-200w")!;
const iphone17 = products.find((p) => p.id === "iphone-17-pro")!;
const pistolaW129 = products.find((p) => p.id === "pistola-rossi-w129")!;
const extratoraW3 = products.find((p) => p.id === "extratora-w3")!;
const kitFerramentas = products.find((p) => p.id === "kit-ferramentas-48v")!;


// === Top 15 produtos importados da famosinhoshop (compráveis com página completa) ===
const famosinho25 = products.find((p) => p.id === "famosinho-25")!;
const famosinho6 = products.find((p) => p.id === "famosinho-6")!;
const famosinho7 = products.find((p) => p.id === "famosinho-7")!;
const famosinho10 = products.find((p) => p.id === "famosinho-10")!;
const famosinho3 = products.find((p) => p.id === "famosinho-3")!;
const famosinho1 = products.find((p) => p.id === "famosinho-1")!;
const famosinho55 = products.find((p) => p.id === "famosinho-55")!;
const famosinho54 = products.find((p) => p.id === "famosinho-54")!;
const famosinho51 = products.find((p) => p.id === "famosinho-51")!;
const famosinho53 = products.find((p) => p.id === "famosinho-53")!;
const famosinho11 = products.find((p) => p.id === "famosinho-11")!;
const famosinho36 = products.find((p) => p.id === "famosinho-36")!;
const famosinho31 = products.find((p) => p.id === "famosinho-31")!;
const famosinho41 = products.find((p) => p.id === "famosinho-41")!;
const famosinho92 = products.find((p) => p.id === "famosinho-92")!;

function buyable(p: typeof famosinho25, shortDesc: string): StoreProduct {
  return {
    id: p.id,
    name: p.name,
    image: p.images[0],
    price: p.price,
    oldPrice: p.oldPrice,
    discount: p.discount,
    rating: p.rating,
    reviews: p.reviews,
    sold: p.sold,
    freeShipping: p.freeShipping,
    description: shortDesc,
    href: `/produto/${p.slug}`,
    slug: p.slug,
  };
}

export const storeProducts: StoreProduct[] = [
  // === Destaques da Loja (Mais Vendidos) ===
  buyable(kitFerramentas, "Kit Completo de Ferramentas Elétricas Sem Fio 48V Sem Escova (Brushless). Furadeira, esmerilhadeira, parafusadeira e chave de impacto com 2 baterias de alta duração e maleta rígida anti-impacto."),
  buyable(lavadora, "Potente, compacta e ideal para limpar carro, calçada, paredes e muito mais. Vem completa com pistola, mangueira e bicos."),
  buyable(extratoraW3, "Extratora e higienizadora portátil que borrifa, esfrega e suga a sujeira profunda de colchões, sofás, poltronas e bancos de carro."),
  buyable(aspirador, "Mini aspirador 3 em 1 com 6000Pa, sem fio e recarregável. Aspira, sopra e infla — perfeito para carro, casa e eletrônicos."),
  buyable(relogio, "Relógio masculino à prova d'água com pulseira em aço inox, movimento Quartz e design inspirado no Submariner. Elegante para qualquer ocasião."),
  buyable(garrafa, "Garrafa térmica de aço inox 650ml com estampa exclusiva da Nossa Senhora Aparecida em aquarela. Mantém fria por 24h e quente por 12h."),
  buyable(boombox, "Caixa de som Aiwa Boombox Plus 200W RMS com Bluetooth 5.3, proteção IP66 contra água e poeira e até 30 horas de bateria. Som potente com qualidade japonesa."),
  buyable(iphone17, "iPhone 17 Pro / Pro Max 256GB original Apple, lacrado e com 1 ano de garantia. Disponível nas cores Azul, Branco e Laranja. Câmera 48MP, chip A19 Pro e tela ProMotion 120Hz."),
  buyable(pistolaW129, "Pistola de Pressão Rossi W129 CO2 4,5mm com sistema blowback realista, slide em metal e ação semi-automática. Vem com maleta, 300 esferas de aço, 5 cilindros CO2, alvos e óleo de silicone."),


  // === Top 15 mais vendidos importados (compráveis) ===
  buyable(famosinho25, "Kit Mochila Rebecca Bonbon coleção 2026 com lancheira térmica, estojo, garrafa, caderno e lip tint oficial. Logo RB em metal e compartimento para notebook."),
  buyable(famosinho6, "Ar Condicionado Portátil HQ 8.500 BTU/h Frio Monofásico Branco. Resfria ambientes com rapidez e praticidade — instalação simples sem obra."),
  buyable(famosinho7, "Ar-Condicionado Portátil Wi-Fi 12.000 BTUs Frio Hisense — controle pelo celular, super silencioso e econômico."),
  buyable(famosinho10, "Piscina com Borda Inflável capacidade 1.000 Litros Pixlar — perfeita para curtir o verão em família com toda segurança."),
  buyable(famosinho3, "Bicicleta Ergométrica Fitness 6kg de inércia com base, ideal para cardio, musculação e queima de gordura em casa."),
  buyable(famosinho1, "Caixa de Som JBL Boombox 3 Bluetooth Preta — som potente, 24h de bateria e proteção IP67 contra água e poeira."),
  buyable(famosinho55, "Alexa Echo Dot 5ª geração original — assistente inteligente com som potente, controle por voz e integração com casa inteligente."),
  buyable(famosinho54, "Caixa de som Joog One Hifi J 200W com 2 microfones sem fio, controle remoto, IP67, app e função TWS."),
  buyable(famosinho51, "Purificador Eletrônico Compacto Efficient com painel digital bivolt — água gelada, natural e fresca em casa."),
  buyable(famosinho53, "Câmera Instax Mini 12 FujiFilm + Filme com 60 poses — fotos instantâneas com qualidade Fujifilm e design moderno."),
  buyable(famosinho11, "Churrasqueira Elétrica Arke para apartamento, rotativa com 5 espetos 220V — pratique churrasco em qualquer lugar."),
  buyable(famosinho36, "Secador de Cabelos Philco PSC3500 4 em 1 dobrável 1450W — design compacto, ideal para viagens."),
  buyable(famosinho31, "Lava Louças Praxis Portátil semi-automática bivolt — economiza água e tempo em qualquer pia."),
  buyable(famosinho41, "Climatizador de Ar 35/60/80 Litros 127V-220V Ventisol PRO CLIN — refresca ambientes grandes com economia."),
  buyable(famosinho92, "Caixa de Som Karaokê Joog X2 300W com tela 10,1\" e 2 microfones — diversão completa com qualidade profissional."),

  // === Vitrine: produtos importados não compráveis (exibem "Indisponível") ===
  {
    id: "famosinho-71",
    name: "Caixa De Som Bluetooth Waaw Hyperboom 1000",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdvj-m0excasdlftxa1",
    price: 69.9,
    oldPrice: 397.9,
    discount: 82,
    rating: 4.9,
    reviews: 492,
    sold: 9853,
    freeShipping: true,
    description: "CAIXA DE SOM BLUETOOTH WAAW BY ALOK HYPERBOOM 1000  180W RMS, IPX7, 12H BATERIA, POWER BASS",
    href: null,
  },
  {
    id: "famosinho-60",
    name: "Smartwatch Redmi Watch 5 Lite GPS Preto Pulseira",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdyw-mc9fnkgv7dqz24",
    price: 69.9,
    oldPrice: 397.9,
    discount: 82,
    rating: 4.9,
    reviews: 492,
    sold: 9853,
    freeShipping: true,
    description: "O smartwatch Redmi Watch 5 Lite Preto é um acessório tecnológico moderno e funcional que complementa seu dia a dia com estilo e praticidade. Com uma tela AMOLED de 1.96\" e design e",
    href: null,
  },
  {
    id: "famosinho-45",
    name: "Panificadora Automática Mondial Master Bread 220V",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rfi7-m3ar0zh6lc9a9a",
    price: 69.9,
    oldPrice: 399.9,
    discount: 83,
    rating: 4.9,
    reviews: 492,
    sold: 9853,
    freeShipping: true,
    description: "Panificadora Automática Mondial Master Bread Branco NPF-54 220VA Panificadora Automática Master Bread Mondial prepara diversos tipos de pães, bolos, pizzas, panetones, além de faze",
    href: null,
  },
  {
    id: "famosinho-33",
    name: "Celular Xiaomi Poco X7 Pro 5g Dual Sim 512gb Amarelo 12ram 50mpx",
    image: "https://http2.mlstatic.com/D_NQ_NP_2X_884323-MLA99500626568_112025-F.webp",
    price: 92.8,
    oldPrice: 497.9,
    discount: 81,
    rating: 4.9,
    reviews: 492,
    sold: 9853,
    freeShipping: true,
    description: "🚀 POCO X7 Pro - Velocidade Máxima, Desempenho ImbatívelO POCO X7 Pro é a combinação perfeita entre poder de processamento, design elegante e tecnologia de ponta. Com um desempenho ",
    href: null,
  },
  {
    id: "famosinho-75",
    name: "Aparelho Jogo De Jantar 30 Peças Orgânico Petroleum Porto Brasil Carlos Bertolazzi + BRINDE",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-8261c-mkckrt97fvgg75",
    price: 69.9,
    oldPrice: 497.9,
    discount: 86,
    rating: 4.9,
    reviews: 492,
    sold: 9843,
    freeShipping: true,
    description: "Transforme suas refeições em momentos especiais com o Aparelho de Jantar 30 Peças Porto Brasil. Produzido em Stoneware, uma tecnologia que garante alta resistência, durabilidade e ",
    href: null,
  },
  {
    id: "famosinho-74",
    name: "Kit 10 Camisetas Dry Fit Masculina - Casual - Treino - Academia - Esportes - Exercícios - Corrida",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdxr-lyatwes75beuc5",
    price: 69.9,
    oldPrice: 397.9,
    discount: 82,
    rating: 4.9,
    reviews: 492,
    sold: 9843,
    freeShipping: true,
    description: "KIT COM 10 CAMISETAS LISAS SORTIDAS",
    href: null,
  },
  {
    id: "famosinho-67",
    name: "Caixa de Som Boombox Plus com 3 Alto-falantes 200W",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rff9-m4ep3f8n12n686",
    price: 69.9,
    oldPrice: 497.9,
    discount: 86,
    rating: 4.9,
    reviews: 491,
    sold: 9831,
    freeShipping: true,
    description: "Reunir nossa família e amigos e desfrutar de uma boa música é um dos prazeres da vida, né? Curta um som potente e de alta definição com a  Boombox Plus  AWS-BBS-01-B! A caixa de so",
    href: null,
  },
  {
    id: "famosinho-43",
    name: "Panela de Pressão Elétrica Electrolux por Rita Lobo 6L Preta Experience Digital (PCC20)",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rfhx-m9yig7n5t2mn18",
    price: 69.9,
    oldPrice: 399.9,
    discount: 83,
    rating: 4.9,
    reviews: 491,
    sold: 9831,
    freeShipping: true,
    description: "A Panela de Pressão Elétrica Electrolux Experience PCC20 assinada pela Chef Rita Lobo traz praticidade e maior segurança no preparo das refeições, tornando suas receitas deliciosas",
    href: null,
  },
  {
    id: "famosinho-65",
    name: "Jogo de Panelas 6 Peças Brinox Antiaderente Ceramic Life Sirius Vanilla e Preto - Com Indução",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcge6chp30vm41",
    price: 69.9,
    oldPrice: 397.9,
    discount: 82,
    rating: 4.9,
    reviews: 487,
    sold: 9740,
    freeShipping: true,
    description: "Jogo de Panelas Brinox Antiaderente Ceramic Life Sirius Vanilla - 6 Peças - Todos os Tipos de Fogões (Inclusive os de Indução e fogões à gás).",
    href: null,
  },
  {
    id: "famosinho-40",
    name: "Bicicleta Spinning Ergométrica Para Exercícios Com Monitor Profissional Sport Suporta até 120kg",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdy6-md1uwolzgyt85c",
    price: 86.9,
    oldPrice: 497.9,
    discount: 83,
    rating: 4.9,
    reviews: 479,
    sold: 9582,
    freeShipping: true,
    description: "Cor: Preto/Vermelho",
    href: null,
  },
  {
    id: "famosinho-39",
    name: "EUHOMY Ar Condicionado Portátil 10.500 BTU/h Frio",
    image: "https://hotsite.fun/images/0bee79220d77ebe7ae7d727a684e0aab_1769059149.webp",
    price: 92.8,
    oldPrice: 497.9,
    discount: 81,
    rating: 4.9,
    reviews: 478,
    sold: 9578,
    freeShipping: true,
    description: "EUHOMY Ar Condicionado Portátil 10.500 BTU/h Frio",
    href: null,
  },
  {
    id: "famosinho-57",
    name: "Caixa Som Sabala DR-908: A Escolha Definitiva para Quem Busca Potência,",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjev4ty4yzghc1",
    price: 69.9,
    oldPrice: 497.9,
    discount: 86,
    rating: 4.9,
    reviews: 476,
    sold: 9531,
    freeShipping: true,
    description: "A Sabala DR-908 é uma caixa de som portátil Bluetooth projetada para quem busca potência, autonomia e presença sonora marcante. Com um design robusto e moderno, ela se destaca como",
    href: null,
  },
  buyable(extratoraW3, "Extratora portátil 3 em 1 que borrifa, esfrega e extrai sujeira de colchões, sofás, estofados e bancos de carro. Higieniza de verdade — você vê a água saindo suja."),
  {
    id: "famosinho-66",
    name: "Jogo de Panelas Cerâmica Kit 5 Peças Antiaderente Tampa Vidro",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mebnfn94x2pt4c",
    price: 69.9,
    oldPrice: 397.86,
    discount: 82,
    rating: 4.9,
    reviews: 452,
    sold: 9052,
    freeShipping: true,
    description: "CONJUNTO PANELAS NAPOLI CERÂMICA",
    href: null,
  },
  {
    id: "famosinho-37",
    name: "Micro-ondas Mondial Mo-01-21-e 1200w 21 Litros",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9zqs2hxtuki59",
    price: 84.9,
    oldPrice: 389.9,
    discount: 78,
    rating: 4.9,
    reviews: 447,
    sold: 8953,
    freeShipping: true,
    description: "DESCRIÇÃO COMPLETA:",
    href: null,
  },
  {
    id: "famosinho-63",
    name: "Sofá 3 Lugares Retrátil e Reclinável Cama inBox Senses 2,00m Velusoft Cinza",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdxn-lzou0oyl6coa73",
    price: 147.9,
    oldPrice: 697.9,
    discount: 79,
    rating: 4.9,
    reviews: 438,
    sold: 8765,
    freeShipping: true,
    description: "Perfeito para quem tem ambiente compacto, o Sofá de 3 Lugares Retrátil e Reclinável Senses é ideal para quem busca unir modernidade, conforto e tamanho para sua sala. Desenvolvido ",
    href: null,
  },
  {
    id: "famosinho-61",
    name: "Bateria Auxiliar De Partida Portátil Com Bomba De Ar de Rosquear",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-8260z-mju7shogkd8jf5",
    price: 69.9,
    oldPrice: 397.9,
    discount: 82,
    rating: 4.9,
    reviews: 438,
    sold: 8765,
    freeShipping: true,
    description: "O BICO DA BOMBA DE AR É DE ROSQUEAR!!!",
    href: null,
  },
  {
    id: "famosinho-68",
    name: "Secadora de Roupa Mueller Solaris 8 kg com timer ar quente e frio 6 varões e 5 cabides",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-malrf6nra3dbc3",
    price: 79.9,
    oldPrice: 497.9,
    discount: 84,
    rating: 4.9,
    reviews: 438,
    sold: 8764,
    freeShipping: true,
    description: "A Secadora de Roupas Solaris oferece 6 varões fixos e mais 5 cabides removíveis que permitem secar vários tipos de roupa ao mesmo tempo.",
    href: null,
  },
  {
    id: "famosinho-64",
    name: "Caixa de Som Bluetooth Boombox BS-01B 200W IP66",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-malte8f3q0opdf",
    price: 69.9,
    oldPrice: 497.9,
    discount: 86,
    rating: 4.9,
    reviews: 437,
    sold: 8754,
    freeShipping: true,
    description: "Som de alta definição para curtir em qualquer lugar",
    href: null,
  },
  {
    id: "famosinho-58",
    name: "Caixa de Som Joog Amplificada Break X1 c/ Tela Touch 13 Microfone Sem Fio, Bluetooth, 800W, Android",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rdvd-mdosx4yka39874",
    price: 69.9,
    oldPrice: 997.87,
    discount: 93,
    rating: 4.9,
    reviews: 437,
    sold: 8753,
    freeShipping: true,
    description: "Som Imersivo e Potente",
    href: null,
  },
  {
    id: "famosinho-47",
    name: "Lava e Seca Midea Master Clean Smart 11kg Wi-Fi MFM01D110WB-TKBR Titanium",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rd5t-lvyp165360qj66",
    price: 247.9,
    oldPrice: 597.9,
    discount: 59,
    rating: 4.9,
    reviews: 433,
    sold: 8675,
    freeShipping: true,
    description: "Desperte para uma nova era de lavanderia com a Lava e Seca Master Clean Smart 11kg da Midea, a máquina que vai revolucionar sua relação com as lavagens de roupas e os afazeres domé",
    href: null,
  },
  {
    id: "famosinho-27",
    name: "Climatizador de Ar Frio Midea 5 Litros Branco e Cinza ACM52 220V",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-824j5-meogihqbtb0la3",
    price: 82.9,
    oldPrice: 497.9,
    discount: 83,
    rating: 4.9,
    reviews: 432,
    sold: 8659,
    freeShipping: true,
    description: "Climatizador de Ar Frio Midea 5 Litros Branco e Cinza ACM52",
    href: null,
  },
  {
    id: "famosinho-42",
    name: "Prancha Pro 480 Turbo MQ Professional Bivolt",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rept-m80tiqdhkwwh87",
    price: 69.9,
    oldPrice: 399.9,
    discount: 83,
    rating: 4.9,
    reviews: 432,
    sold: 8654,
    freeShipping: true,
    description: "A prancha Turbo você fará progressivas perfeitas muito mais rápido e com o melhor custo-benefício. Seu dia vai render com a agilidade e a temperatura da prancha MQ Pro480 Turbo Tit",
    href: null,
  },
  {
    id: "famosinho-32",
    name: "Caixa de Som JBL Boombox 4 Bluetooth 210W Preta Bivolt",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-824i8-mdyu6aqj7g1td8",
    price: 96.78,
    oldPrice: 497.9,
    discount: 81,
    rating: 4.9,
    reviews: 428,
    sold: 8569,
    freeShipping: true,
    description: "🔊 Caixa de Som JBL Portátil Boombox 4Eleve sua experiência musical com som imbatível e design incrível!",
    href: null,
  },
  {
    id: "famosinho-38",
    name: "Fritadeira Air Fryer Forno Oven 12L Mondial Preto e Inox0W AFON-12L-BI",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7raui-mb4awu05e15c16",
    price: 69.9,
    oldPrice: 397.9,
    discount: 82,
    rating: 4.9,
    reviews: 419,
    sold: 8391,
    freeShipping: true,
    description: "A Air Fryer AFON-12L-BI da Mondial é 2 em 1: Fritadeira a Ar com o espaço e a versatilidade do forno. Você pode assar, cozinhar e fritar sem óleo e produzir receitas muito mais sau",
    href: null,
  },
  {
    id: "famosinho-70",
    name: "Jogo de Panelas 13 Peças Ferro Fundido Esmaltado Premium Alta Resistência Antibacteria Mantenha aquecido e fresco",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mk3m0dsr37k1a6",
    price: 79.9,
    oldPrice: 497.9,
    discount: 84,
    rating: 4.9,
    reviews: 398,
    sold: 7965,
    freeShipping: true,
    description: "Coleção Select Cook KINETX  LE FRANCE",
    href: null,
  },
  {
    id: "famosinho-49",
    name: "Pad 11 Geração A16 256GB Wi-fi Tela 11pol Original Novo Lacrado com Garantia  de 1 ano",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mdh7rladn00h24",
    price: 94.9,
    oldPrice: 497.9,
    discount: 81,
    rating: 4.9,
    reviews: 382,
    sold: 7654,
    freeShipping: true,
    description: "O iPad de 11 polegadas está poderoso como nunca com o chip A16 super-rápido, tela Liquid Retina, câmeras avançadas, conexão Wi-Fi 6 veloz e porta USB-C. Disponível em quatro cores,",
    href: null,
  },
  {
    id: "famosinho-107",
    name: "Aparelho de Jantar/Chá Oxford Ryo Maresia 30 Peças",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rd5p-m7uwvu85tnp9ae",
    price: 69.9,
    oldPrice: 497.9,
    discount: 86,
    rating: 4.9,
    reviews: 382,
    sold: 7643,
    freeShipping: true,
    description: "Características do produto:",
    href: null,
  },
  {
    id: "famosinho-13",
    name: "Churrasqueira Resistente Modelo Rodeio Bacia Esmaltada Casa Praia Piscina Verão Lazer Preta - Mor",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7reng-m1ya6at9aqw05a",
    price: 129.3,
    oldPrice: 499,
    discount: 74,
    rating: 4.9,
    reviews: 377,
    sold: 7548,
    freeShipping: true,
    description: "A Churrasqueira Rodeio da Mor é ideal para preparar um saboroso churrasco. Equipada com uma grade multiuso, permite fazer diversos tipos de assados. Inclui uma tábua de madeira par",
    href: null,
  },
  {
    id: "famosinho-12",
    name: "Churrasqueira Portátil A Carvão Biscuitt Steak Master Smoke & Fire USB Com Bag",
    image: "https://down-br.img.susercontent.com/file/br-11110105-7r98o-lr96mg3y7nja34",
    price: 149.9,
    oldPrice: 624.9,
    discount: 76,
    rating: 4.9,
    reviews: 377,
    sold: 7543,
    freeShipping: true,
    description: "A qualquer hora e em qualquer lugar, ninguém resiste a um bom churrasco",
    href: null,
  },
  {
    id: "famosinho-29",
    name: "Chuveiro Acqua Duo Lorenzetti BIVOLT",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rccw-ltobhzgc83yx8a",
    price: 69.8,
    oldPrice: 497.9,
    discount: 86,
    rating: 4.9,
    reviews: 348,
    sold: 6978,
    freeShipping: true,
    description: "🚿 CHUVEIRO LORENZETTI ACQUA DUOSofisticação, tecnologia e o banho do seu jeitoO Lorenzetti Acqua Duo Preto Fosco é a evolução da consagrada Linha Acqua Ultra. Com design moderno em",
    href: null,
  },
  {
    id: "famosinho-26",
    name: "Ar Condicionado Portátil HQ 10.500 BTU/h Frio Branco HQ-AP10500FW",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rccm-m6cyop52wbiwb1",
    price: 92.8,
    oldPrice: 497.9,
    discount: 81,
    rating: 4.9,
    reviews: 299,
    sold: 5987,
    freeShipping: true,
    description: "Ar Condicionado Portátil HQ 10.500 BTU/h Frio Monofásico Branco HQ-AP10500FW",
    href: null,
  },
  {
    id: "famosinho-24",
    name: "Ar Condicionado Portátil LG Dual Inverter 14.000 Btu Bivolt",
    image: "https://http2.mlstatic.com/D_NQ_NP_908926-MLA43324938497_082020-O-ar-condicionado-portatil-lg-dual-inverter-14000-btu-127v.webp",
    price: 92.8,
    oldPrice: 597.9,
    discount: 84,
    rating: 4.9,
    reviews: 294,
    sold: 5889,
    freeShipping: true,
    description: "O Ar Condicionado Portátil LG Dual Inverter 14.000 BTU é a solução ideal para quem busca conforto e eficiência em climatização. Com uma potência de refrigeração de 14.000 BTU, este",
    href: null,
  },
  {
    id: "famosinho-28",
    name: "Caixa De Som Bluetooth 200w 39000mah Tws Ipx6 Sabala Dr-909 Preto 127/220v",
    image: "https://http2.mlstatic.com/D_NQ_NP_2X_610041-MLB96030304778_102025-F.webp",
    price: 69.8,
    oldPrice: 497.9,
    discount: 86,
    rating: 4.9,
    reviews: 293,
    sold: 5867,
    freeShipping: true,
    description: "🔊 CAIXA DE SOM BLUETOOTH SABALA 200WPotência, bateria gigante e som de festa onde você estiverTransforme qualquer lugar em um verdadeiro evento com a Caixa de Som Bluetooth SABALA.",
    href: null,
  },
  {
    id: "famosinho-14",
    name: "Kit 6 Cadeira de Praia Aço Mor 110kg Resistente CORES SORTIDAS Oferta",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7reoq-m8kskp1ohv2vcf",
    price: 89,
    oldPrice: 399.9,
    discount: 78,
    rating: 4.9,
    reviews: 283,
    sold: 5668,
    freeShipping: true,
    description: "!!! ATENÇÃO !!!!!",
    href: null,
  },
  {
    id: "famosinho-35",
    name: "Kit Lattafa Yara Collection Feminino Edp - Perfume 4x25ml original",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mh12vhr254hs6c",
    price: 69.9,
    oldPrice: 397.9,
    discount: 82,
    rating: 4.9,
    reviews: 274,
    sold: 5490,
    freeShipping: true,
    description: "Transforme seu Estilo com o Kit Lattafa Yara Collection EDP - 4 Fragrâncias Exclusivas! 💖✨",
    href: null,
  },
  {
    id: "famosinho-52",
    name: " SWITCH  DESBLOQUEADO + 10 JOGOS DA SUA ESCOLHA COM CARTÃO DE MEMORIA 128 GB",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m024asxqvazr6b",
    price: 64.9,
    oldPrice: 497.9,
    discount: 87,
    rating: 4.9,
    reviews: 273,
    sold: 5462,
    freeShipping: true,
    description: "Bem vindo a nossa loja",
    href: null,
  },
  {
    id: "famosinho-97",
    name: "Kit conjunto de panelas de ferro esmaltadas luxo 18 peças",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mj765kpbq3nla8",
    price: 79.9,
    oldPrice: 697.9,
    discount: 89,
    rating: 4.9,
    reviews: 271,
    sold: 5432,
    freeShipping: true,
    description: "Coleção Select Cook 18 peças kit",
    href: null,
  },
  {
    id: "famosinho-5",
    name: "Caixa de Som Amplificada AIWA Party Box AWSPB07 Bluetooth",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m688tqkxlw36d9",
    price: 149.99,
    oldPrice: 990,
    discount: 85,
    rating: 4.9,
    reviews: 268,
    sold: 5367,
    freeShipping: true,
    description: "DESCRIÇÃO COMPLETA:",
    href: null,
  },
  {
    id: "famosinho-18",
    name: "Bola De Futebol De Campo Penalty Bravo Xxv",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rbkz-m5oo5ljc9heg98",
    price: 49,
    oldPrice: 129.99,
    discount: 62,
    rating: 4.9,
    reviews: 267,
    sold: 5346,
    freeShipping: true,
    description: "Prepare-se para elevar o seu jogo a um novo patamar com a Bola de Futebol de Campo Penalty Bravo!     Desenvolvida com tecnologia de ponta e materiais de alta performance, esta Bol",
    href: null,
  },
  {
    id: "famosinho-72",
    name: "Kit compre 1 leve 2 Camisa Seleção Brasil Home Copa 2026",
    image: "https://meu-pedido.sbs/images/743c81c8e45956c8395c961228aae233_1774470483.webp",
    price: 129.9,
    oldPrice: 597.9,
    discount: 78,
    rating: 4.9,
    reviews: 266,
    sold: 5331,
    freeShipping: true,
    description: "KIT EXCLUSIVO – COMPRE 1 LEVE 2CAMISAS SELEÇÃO BRASILEIRA 2026 (AMARELA + AZUL) 🇧🇷🔥",
    href: null,
  },
  {
    id: "famosinho-100",
    name: "Jogo De Panela Avant Space 5 Peças - Tognana Cor Preto",
    image: "https://http2.mlstatic.com/D_NQ_NP_747089-MLA96155562431_102025-O.webp",
    price: 79.9,
    oldPrice: 647.9,
    discount: 88,
    rating: 4.9,
    reviews: 266,
    sold: 5324,
    freeShipping: true,
    description: "Jogo de Panelas Avant Space – Praticidade e Design PremiadoGanhe espaço na cozinha! Panelas empilháveis que otimizam seu armário e geladeira.",
    href: null,
  },
  {
    id: "famosinho-46",
    name: "Detergente Limpador Para Extratoras Limpa E Extrai 1L Wap",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7qve4-lgjjzn7opmtfae",
    price: 19.99,
    oldPrice: 39.9,
    discount: 50,
    rating: 4.9,
    reviews: 249,
    sold: 4983,
    freeShipping: true,
    description: "Limpador Concentrado Baixa Espumação para Extratoras Limpa e Extrai 1 Litro Wap",
    href: null,
  },
  {
    id: "famosinho-9",
    name: "Piscina Splash Fun Redonda Inflável 2400 Litros - Mor",
    image: "https://down-br.img.susercontent.com/file/br-11134201-22120-c8r0xtce3plv81",
    price: 139.99,
    oldPrice: 349,
    discount: 60,
    rating: 4.9,
    reviews: 183,
    sold: 3676,
    freeShipping: true,
    description: "Piscina Splash Fun Redonda Inflável 2400 Litros - Mor",
    href: null,
  },
  {
    id: "famosinho-56",
    name: " Mini Internet rápida Via Satélite Antena Original Garantia de 01 ano ENVIO IMEDIATO",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-md1zj59a435t8d",
    price: 94.9,
    oldPrice: 497.9,
    discount: 81,
    rating: 4.9,
    reviews: 100,
    sold: 2000,
    freeShipping: true,
    description: "Olá amigos,",
    href: null,
  },
  {
    id: "famosinho-2",
    name: "Fritadeira Elétrica Visio Fry Elgin 5L 1700w Air Fryer Digital Cinza",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mh9e1c37asxxe2",
    price: 124.99,
    oldPrice: 500,
    discount: 75,
    rating: 4.9,
    reviews: 100,
    sold: 2000,
    freeShipping: true,
    description: "Fritadeira Elétrica Sem Óleo Elgin Visio Fry 5L  Praticidade, potência e visualização total do preparo",
    href: null,
  },
  {
    id: "famosinho-19",
    name: "Colchão Inflável Suporta 300kg Casal Camping Praia + Bomba de Ar Manual Bestway",
    image: "https://down-br.img.susercontent.com/file/br-11110105-7r98o-lzz84v13yu7c19",
    price: 69,
    oldPrice: 195.11,
    discount: 65,
    rating: 4.9,
    reviews: 76,
    sold: 1531,
    freeShipping: true,
    description: "A bomba de ar é enviada dentro da caixa junto com o colchão.",
    href: null,
  },
  {
    id: "famosinho-16",
    name: "Tablet Vision TAB 7 Stitch + Capa e Bolsa - Octa-Core 3GB RAM 64GB Android 14 Go Wi-Fi IPS Positivo",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m84xjaeqeia9c4",
    price: 137,
    oldPrice: 799,
    discount: 83,
    rating: 4.9,
    reviews: 50,
    sold: 987,
    freeShipping: true,
    description: "Condições do Produto",
    href: null,
  },
  {
    id: "famosinho-17",
    name: "Bicicleta  Aro 29 GT Sprint MX7 24V index Freio Disco Alumínio Suspensão Aero MTB",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-me910y70d7nmf6",
    price: 147,
    oldPrice: 799,
    discount: 82,
    rating: 4.9,
    reviews: 50,
    sold: 984,
    freeShipping: true,
    description: "ESCOLHA O TAMANHO DO QUADRO:",
    href: null,
  },
  {
    id: "famosinho-21",
    name: "Triciclo Infantil 4 em 1 Multifuncional Carrinho de Bebê Com Empurrador e CapotaSolar-Kababy",
    image: "https://down-br.img.susercontent.com/file/br-11110105-7r98o-lvfax7xdk1xob6",
    price: 159.9,
    oldPrice: 599,
    discount: 73,
    rating: 4.9,
    reviews: 50,
    sold: 897,
    freeShipping: true,
    description: "Explore o mundo com o triciclo multifuncional da KaBaby, um companheiro que cresce com seu filho por ter diversas funcionalidades tecnológicas que se ajustam ao dia a dia e ao cres",
    href: null,
  },
  {
    id: "famosinho-108",
    name: "Jogo de Jantar Canyon Porcelana Decorada 20 Peças Tramontina",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-81zwa-mimr7kh9srno54",
    price: 69.9,
    oldPrice: 596.9,
    discount: 88,
    rating: 4.9,
    reviews: 50,
    sold: 877,
    freeShipping: true,
    description: "Jogo de Jantar Canyon Porcelana Decorada 20 Peças Tramontina",
    href: null,
  },
  {
    id: "famosinho-22",
    name: "Bicicleta Aro 20 Bmx infantil GottBikes Freio V-Brake",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mer4ub5zgb9c1b",
    price: 109,
    oldPrice: 569,
    discount: 81,
    rating: 4.9,
    reviews: 50,
    sold: 769,
    freeShipping: true,
    description: "Seja o mestre da adrenalina com nossa incrível bicicleta BMX aro 20! Projetada para oferecer uma experiência única de emoção e diversão sobre duas rodas, nossa bicicleta combina um",
    href: null,
  },
  {
    id: "famosinho-80",
    name: "Caixa de Som WAAW Hyperboom 1000 180W IPX7 TWS Bivolt",
    image: "https://down-br.img.susercontent.com/file/br-11134207-820lo-mlgqr9tonx8kc2",
    price: 126.9,
    oldPrice: 1260.9,
    discount: 90,
    rating: 4.9,
    reviews: 50,
    sold: 500,
    freeShipping: true,
    description: "Importante: Após a confirmação do pagamento, não realizamos cancelamento de pedidos. Em caso de dúvidas, recomendamos entrar em contato antes de finalizar a compra.",
    href: null,
  },
  {
    id: "famosinho-23",
    name: "Carrinho de Bebê Guarda Chuva Passeio Leve e Dobrável Mega Compras Compacto, Seguro,Cinto",
    image: "https://down-br.img.susercontent.com/file/br-11110105-7r98o-lw4k47nf6k7mdf",
    price: 94.9,
    oldPrice: 349.9,
    discount: 73,
    rating: 4.9,
    reviews: 50,
    sold: 458,
    freeShipping: true,
    description: "\"Na Mega Compras ficou Mega fácil encontrar\"",
    href: null,
  },
  {
    id: "famosinho-8",
    name: "Climatizador de Ar 5,3L Oster Portátil 4 em 1",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-82590-mfv41lm1ui2zf4",
    price: 149.9,
    oldPrice: 649,
    discount: 77,
    rating: 4.9,
    reviews: 50,
    sold: 341,
    freeShipping: true,
    description: "Design, tecnologia e performance no clima certo. Beleza e Frescor para você levar aonde for Conheça o novo climatizador Oster portátil. Ele proporciona um ambiente mais fresco, sej",
    href: null,
  },
  {
    id: "famosinho-101",
    name: "Pipoqueira Classic Retrô, Misturador Automático, Com Bandeja Para Servir Pipoca PPI04V Philco",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-ma357gbfhypu7c",
    price: 643.08,
    oldPrice: 2572.32,
    discount: 75,
    rating: 4.9,
    reviews: 50,
    sold: 215,
    freeShipping: true,
    description: "Pipoqueira Philco Classic Retrô PPI04V",
    href: null,
  },
  {
    id: "famosinho-91",
    name: "Panificadora 19 Programas Gallant 600w Preta (GPA1E19A_127PT)",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mg5ie67i1vk735",
    price: 69.9,
    oldPrice: 589.9,
    discount: 88,
    rating: 4.9,
    reviews: 50,
    sold: 200,
    freeShipping: true,
    description: "PANIFICADORA 19 PROGRAMAS GALLANT 600W PRETA (GPA1E19A)",
    href: null,
  },
  {
    id: "famosinho-106",
    name: "YESOP Máquina De Gelo Portátil Preto 12kg/dia 127V Produção Rápida Turbo Ice Para Casa E Bar",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9o8h6dyt2d529",
    price: 48.05,
    oldPrice: 398.05,
    discount: 88,
    rating: 4.9,
    reviews: 50,
    sold: 200,
    freeShipping: true,
    description: "YESOP Máquina De Gelo Portátil Preto 12kg/dia 127V Produção Rápida Turbo Ice Para Casa E Bar",
    href: null,
  },
  {
    id: "famosinho-81",
    name: "Lava e Seca 11kg Hisense 11 Programas de Lavagem, Steam, Wi-fi Titanium",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-man0mifag5bt63",
    price: 257.9,
    oldPrice: 2579,
    discount: 90,
    rating: 4.9,
    reviews: 50,
    sold: 150,
    freeShipping: true,
    description: "******PRODUTO REEMBALADO******",
    href: null,
  },
  {
    id: "famosinho-78",
    name: "Lava Louças Praxis Portátil LLPP Semi-Automática 127V Branca",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m850ox5881ld7a",
    price: 64.9,
    oldPrice: 864.9,
    discount: 92,
    rating: 4.9,
    reviews: 50,
    sold: 131,
    freeShipping: true,
    description: "Lava Louças Praxis Portátil LLPP Semi-Automática 127V Branca",
    href: null,
  },
  {
    id: "famosinho-77",
    name: "Extratora e Higienizadora Portátil WAP Spot Cleaner 127V FW009214",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjh1ba8fml8m56",
    price: 85.9,
    oldPrice: 685.9,
    discount: 87,
    rating: 4.9,
    reviews: 50,
    sold: 120,
    freeShipping: true,
    description: "VENDIDO POR COMASP FERRAMENTAS | ENVIO IMEDIATO",
    href: null,
  },
  {
    id: "famosinho-87",
    name: "Caixa De Som Joog break X1 Tela 13,1 2 Microfones Cor Preto 110V/220V",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m8jnvlvbqyghe4",
    price: 149.9,
    oldPrice: 1490.9,
    discount: 90,
    rating: 4.9,
    reviews: 50,
    sold: 100,
    freeShipping: true,
    description: "O Joog JOOG X1 oferece um som natural, com grande clareza e precisão, que é uniformemente disperso. Um alto-falante que garante potência e qualidade por igual na reprodução de cont",
    href: null,
  },
  {
    id: "famosinho-79",
    name: "Panificadora 19 Programas Gallant 600w 127v Branca (GPA1E19A_127BR)",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mg5ie67i4op35d",
    price: 85.9,
    oldPrice: 398.9,
    discount: 78,
    rating: 4.9,
    reviews: 50,
    sold: 100,
    freeShipping: true,
    description: "PANIFICADORA 19 PROGRAMAS GALLANT 600W BRANCA (GPA1E19A).",
    href: null,
  },
  {
    id: "famosinho-30",
    name: "Mochila Escolar Bluey E Bingo 15l Kit Meninas Com Lancheira",
    image: "https://http2.mlstatic.com/D_NQ_NP_2X_629077-MLB99739738865_112025-F-mochila-escolar-bluey-e-bingo-15l-kit-meninas-com-lancheira.webp",
    price: 369,
    oldPrice: 1476,
    discount: 75,
    rating: 4.9,
    reviews: 50,
    sold: 50,
    freeShipping: true,
    description: "Descrição do Kit de Mochila Bluey",
    href: null,
  },
  {
    id: "famosinho-102",
    name: "Conjunto de Panelas de Ferro Fundido Esmaltado 10 Peças - Frigideira e Panelas Antiaderentes",
    image: "https://down-br.img.susercontent.com/file/br-11134207-820mb-ml9zyiobgzrb67",
    price: 598,
    oldPrice: 2392,
    discount: 75,
    rating: 4.9,
    reviews: 50,
    sold: 37,
    freeShipping: true,
    description: "Eleve sua experiência na cozinha com oConjunto de Panelas de Ferro Fundido Esmaltado 10 Peças! Ideal para quem busca sabor, durabilidade e versatilidade, cada peça é projetada para",
    href: null,
  },
  {
    id: "famosinho-109",
    name: "Conjunto de 12 Copos De Cristal P/ Long Drink 490Ml Proper Effect",
    image: "https://down-br.img.susercontent.com/file/d8f8f5450da9553d8273c5ffe8a1ee61",
    price: 69.9,
    oldPrice: 397.9,
    discount: 82,
    rating: 4.9,
    reviews: 50,
    sold: 1,
    freeShipping: true,
    description: "A Oxford Alumina Crystal traz alta tecnologia para o mundo dos cristais. O processo inovador de produção e a adição de Alumina na sua composição conferem ao produto características",
    href: null,
  },
  {
    id: "famosinho-105",
    name: "Bicicleta Bike Ergometrica Spinning Academia Fitness Profissional 120kg",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m78dqlbsalos96",
    price: 606.28,
    oldPrice: 2425.12,
    discount: 75,
    rating: 4.9,
    reviews: 50,
    sold: 0,
    freeShipping: true,
    description: "A bicicleta ergométrica Bike Sport é uma excelente opção para melhorar a saúde cardiovascular, controlar a pressão arterial e reduzir o impacto nas articulações. Além disso, auxili",
    href: null,
  },
  {
    id: "famosinho-95",
    name: "Conjunto Feminino de Trabalho em Alfaiataria Laris Blusa com Botões e Calça Social",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81ztc-misy16cf0dmr4f",
    price: 170.05,
    oldPrice: 680.2,
    discount: 75,
    rating: 4.9,
    reviews: 50,
    sold: 0,
    freeShipping: true,
    description: "Tecido:Alfaiataria Laris(Tipo terno)",
    href: null,
  },
  {
    id: "famosinho-94",
    name: "KISSMELADY 015 010 8110 com cinto preto calça mom jeans feminina moda novo  lisa sem rascada",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lx8mbd4xa1fj24",
    price: 77.97,
    oldPrice: 199,
    discount: 61,
    rating: 4.9,
    reviews: 50,
    sold: 0,
    freeShipping: true,
    description: "A modelo está usando tamanho p ou 36",
    href: null,
  },
  {
    id: "famosinho-76",
    name: "Porto Brasil Aparelho De Jantar 30 Peças Orgânico Petroleum",
    image: "https://down-br.img.susercontent.com/file/sg-11134201-7rbkw-m64im3p5ih5a46",
    price: 812.63,
    oldPrice: 3250.52,
    discount: 75,
    rating: 4.9,
    reviews: 50,
    sold: 0,
    freeShipping: true,
    description: "O Stoneware, assim como a faiança feldspática e porcelana, é um material cerâmico. O Stoneware Porto Brasil é um material inovador e sustentável, onde a combinação das melhores mat",
    href: null,
  },
  {
    id: "famosinho-50",
    name: "Starlink V4 Internet Satélite Wi-fi 6 Alta Velocidade Nacional Homologada Anatel (Starlink Padrão)",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-me8xwns11f5v8f",
    price: 94.9,
    oldPrice: 497.9,
    discount: 81,
    rating: 4.9,
    reviews: 50,
    sold: 0,
    freeShipping: true,
    description: "Olá amigos,",
    href: null,
  },
  {
    id: "famosinho-20",
    name: "Conjunto De 24 Potes Herméticos Croix Com Tampa E Trava",
    image: "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mci5ecdv44s2e5",
    price: 64.99,
    oldPrice: 177.99,
    discount: 63,
    rating: 4.9,
    reviews: 50,
    sold: 0,
    freeShipping: true,
    description: "DESCRIÇÃO RESUMIDA",
    href: null,
  },
  {
    id: "famosinho-15",
    name: "Kit Praia 4 Cadeiras Sortidas Reclinável + Guarda Sol Fashion + Saca Areia+ Carrinho+ Coller 18 Lts",
    image: "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mhuv620f45j7bf",
    price: 129.9,
    oldPrice: 699,
    discount: 81,
    rating: 4.9,
    reviews: 535,
    sold: 10706,
    freeShipping: true,
    description: "O Verão está aí, e que tal aquele Kit Completo para aproveitar com a família e amigos na praia?",
    href: null,
  },

  // === Ferramentas de exemplo (vitrine fixa original) ===
  {
    id: "parafusadeira-20v",
    name: "Parafusadeira/Furadeira de Impacto 20V Black+Decker com Bateria e Maleta",
    image: parafusadeira,
    price: 289.9,
    oldPrice: 599.9,
    discount: 51,
    rating: 4.9,
    reviews: 1248,
    sold: 5320,
    freeShipping: true,
    description: "Mandril 3/8\", 2 velocidades, 20 níveis de torque. Inclui bateria de lítio 20V e carregador.",
    href: null,
  },
  {
    id: "esmerilhadeira-bosch",
    name: "Esmerilhadeira Angular 4.1/2'' Bosch GWS 850W com Disco",
    image: esmerilhadeira,
    price: 219.9,
    oldPrice: 399.0,
    discount: 45,
    rating: 4.8,
    reviews: 873,
    sold: 3421,
    freeShipping: true,
    description: "Potência de 850W, ideal para corte e desbaste de metais e alvenaria. Acompanha disco e empunhadura lateral.",
    href: null,
  },
  {
    id: "furadeira-impacto-750",
    name: "Furadeira de Impacto 750W com Mandril e Maleta",
    image: furadeira,
    price: 159.9,
    oldPrice: 329.9,
    discount: 51,
    rating: 4.7,
    reviews: 612,
    sold: 2890,
    freeShipping: true,
    description: "Mandril 13mm, velocidade variável, função impacto para concreto. Perfeita para uso doméstico e profissional.",
    href: null,
  },
  {
    id: "serra-circular-1400",
    name: "Serra Circular 7.1/4'' 1400W Hitachi com Disco e Guia",
    image: serra,
    price: 449.0,
    oldPrice: 799.0,
    discount: 44,
    rating: 4.9,
    reviews: 421,
    sold: 1640,
    freeShipping: true,
    description: "Profundidade de corte 65mm, motor 1400W, base de alumínio reforçado. Acompanha disco widia 24 dentes.",
    href: null,
  },
  {
    id: "kit-ferramentas-110",
    name: "Kit Ferramentas 110 Peças com Maleta - Chaves, Alicates e Soquetes",
    image: kit,
    price: 199.9,
    oldPrice: 449.9,
    discount: 56,
    rating: 4.9,
    reviews: 2104,
    sold: 8930,
    freeShipping: true,
    description: "Maleta organizadora com 110 peças: chaves de fenda, philips, alicates, martelo, jogo de soquetes e muito mais.",
    href: null,
  },
];
