/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutPagamentoRouteImport } from './routes/checkout.pagamento'
import { Route as CheckoutEnderecoRouteImport } from './routes/checkout.endereco'
import { Route as ApiPublicFreepayWebhookRouteImport } from './routes/api/public/freepay-webhook'
import { Route as ApiPublicFlevopayWebhookRouteImport } from './routes/api/public/flevopay-webhook'

const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPagamentoRoute = CheckoutPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutEnderecoRoute = CheckoutEnderecoRouteImport.update({
  id: '/endereco',
  path: '/endereco',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiPublicFreepayWebhookRoute = ApiPublicFreepayWebhookRouteImport.update({
  id: '/api/public/freepay-webhook',
  path: '/api/public/freepay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlevopayWebhookRoute =
  ApiPublicFlevopayWebhookRouteImport.update({
    id: '/api/public/flevopay-webhook',
    path: '/api/public/flevopay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/loja': typeof LojaRoute
  '/checkout/endereco': typeof CheckoutEnderecoRoute
  '/checkout/pagamento': typeof CheckoutPagamentoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/api/public/flevopay-webhook': typeof ApiPublicFlevopayWebhookRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/checkout/endereco': typeof CheckoutEnderecoRoute
  '/checkout/pagamento': typeof CheckoutPagamentoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/checkout': typeof CheckoutIndexRoute
  '/api/public/flevopay-webhook': typeof ApiPublicFlevopayWebhookRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/loja': typeof LojaRoute
  '/checkout/endereco': typeof CheckoutEnderecoRoute
  '/checkout/pagamento': typeof CheckoutPagamentoRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/api/public/flevopay-webhook': typeof ApiPublicFlevopayWebhookRoute
  '/api/public/freepay-webhook': typeof ApiPublicFreepayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/loja'
    | '/checkout/endereco'
    | '/checkout/pagamento'
    | '/checkout/sucesso'
    | '/produto/$slug'
    | '/checkout/'
    | '/api/public/flevopay-webhook'
    | '/api/public/freepay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loja'
    | '/checkout/endereco'
    | '/checkout/pagamento'
    | '/checkout/sucesso'
    | '/produto/$slug'
    | '/checkout'
    | '/api/public/flevopay-webhook'
    | '/api/public/freepay-webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/loja'
    | '/checkout/endereco'
    | '/checkout/pagamento'
    | '/checkout/sucesso'
    | '/produto/$slug'
    | '/checkout/'
    | '/api/public/flevopay-webhook'
    | '/api/public/freepay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LojaRoute: typeof LojaRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicFlevopayWebhookRoute: typeof ApiPublicFlevopayWebhookRoute
  ApiPublicFreepayWebhookRoute: typeof ApiPublicFreepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/pagamento': {
      id: '/checkout/pagamento'
      path: '/pagamento'
      fullPath: '/checkout/pagamento'
      preLoaderRoute: typeof CheckoutPagamentoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/endereco': {
      id: '/checkout/endereco'
      path: '/endereco'
      fullPath: '/checkout/endereco'
      preLoaderRoute: typeof CheckoutEnderecoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/public/freepay-webhook': {
      id: '/api/public/freepay-webhook'
      path: '/api/public/freepay-webhook'
      fullPath: '/api/public/freepay-webhook'
      preLoaderRoute: typeof ApiPublicFreepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flevopay-webhook': {
      id: '/api/public/flevopay-webhook'
      path: '/api/public/flevopay-webhook'
      fullPath: '/api/public/flevopay-webhook'
      preLoaderRoute: typeof ApiPublicFlevopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutEnderecoRoute: typeof CheckoutEnderecoRoute
  CheckoutPagamentoRoute: typeof CheckoutPagamentoRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutEnderecoRoute: CheckoutEnderecoRoute,
  CheckoutPagamentoRoute: CheckoutPagamentoRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  LojaRoute: LojaRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicFlevopayWebhookRoute: ApiPublicFlevopayWebhookRoute,
  ApiPublicFreepayWebhookRoute: ApiPublicFreepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
